# Generated by Django 4.2.1 on 2023-05-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='max_players',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='user',
            name='max_players',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='group_traning',
            name='price',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='prov_traning',
            name='price',
            field=models.CharField(default='Gratis', max_length=50),
        ),
        migrations.AlterField(
            model_name='pt_traning',
            name='price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
